// Inlines engine.js into index.html between the ENGINE-START / ENGINE-END markers.
import fs from 'node:fs';
const eng = fs.readFileSync('engine.js', 'utf8');
const block = eng.slice(eng.indexOf('/* ENGINE-START'), eng.indexOf('/* ENGINE-END */') + '/* ENGINE-END */'.length);
let html = fs.readFileSync('index.html', 'utf8');
const i = html.indexOf('ENGINE-START'); const a = html.lastIndexOf('/*', i), b = html.indexOf('/* ENGINE-END */') + '/* ENGINE-END */'.length;
if (a < 0 || b < 16) throw new Error('markers not found in index.html');
html = html.slice(0, a) + block + html.slice(b);
fs.writeFileSync('index.html', html);
console.log('inlined engine:', block.length, 'chars');

// Generate api/_context.js: the knowledge the dough coach is grounded in (model doc + field notes).
const modelDoc = fs.readFileSync('research/DOUGH-MODEL.md', 'utf8');
const handoff = fs.readFileSync('neapolitan-pizza-handoff.md', 'utf8');
// keep the dough-relevant sections of the handoff (oven, flour, dough, shaping, core principles); drop shopping/menu detail
const keep = ['## 1. THE OVEN', '## 2. FLOUR', '## 3. THE DOUGH', '## 4. SHAPING', '## 16. CORE PRINCIPLES'];
const sections = handoff.split(/\n(?=## )/);
const fieldNotes = sections.filter(s => keep.some(k => s.startsWith(k))).join('\n\n')
  .replace(/\*\*User:\*\*.*\n/g, '');
fs.mkdirSync('api', { recursive: true });
fs.writeFileSync('api/_context.js', `// GENERATED by build.mjs — do not edit.\nmodule.exports = { MODEL_DOC: ${JSON.stringify(modelDoc)}, FIELD_NOTES: ${JSON.stringify(fieldNotes)} };\n`);
console.log('coach context:', modelDoc.length + fieldNotes.length, 'chars');
